name: Waka Readme

on:
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: spideynolove/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
